# Generated by Django 5.1.2 on 2024-10-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('area', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='متراژ')),
                ('year_built', models.IntegerField(verbose_name='سال ساخت')),
                ('floor', models.IntegerField(verbose_name='طبقه')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('elevator', models.BooleanField(default=False, verbose_name='آسانسور')),
                ('storage', models.BooleanField(default=False, verbose_name='انباری')),
            ],
            options={
                'verbose_name': 'آگهی املاک',
                'verbose_name_plural': 'آگهی\u200cهای املاک',
            },
        ),
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('vehicle_type', models.CharField(choices=[('car', 'خودرو'), ('motorcycle', 'موتورسیکلت'), ('truck', 'کامیون')], max_length=50, verbose_name='نوع وسیله نقلیه')),
                ('model', models.CharField(max_length=100, verbose_name='مدل')),
                ('color', models.CharField(max_length=50, verbose_name='رنگ')),
                ('mileage', models.IntegerField(verbose_name='کارکرد')),
                ('fuel_type', models.CharField(max_length=50, verbose_name='نوع سوخت')),
            ],
            options={
                'verbose_name': 'آگهی وسیله نقلیه',
                'verbose_name_plural': 'آگهی\u200cهای وسایل نقلیه',
            },
        ),
        migrations.CreateModel(
            name='VehiclePartListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('location', models.CharField(max_length=255, verbose_name='موقعیت')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('part_name', models.CharField(max_length=255, verbose_name='نام قطعه')),
            ],
            options={
                'verbose_name': 'آگهی قطعات وسایل نقلیه',
                'verbose_name_plural': 'آگهی\u200cهای قطعات وسایل نقلیه',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='listings.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
    ]
